import { ACTION_TYPE, ActionType } from "@/constants/type";
export const P1_ACTION_LIST: ActionType[] = [
    ACTION_TYPE.DOUBLE_ATTACK,
    ACTION_TYPE.POISON,
    ACTION_TYPE.ATTACK,
    ACTION_TYPE.ATTACK,
    ACTION_TYPE.ATTACK,
    ACTION_TYPE.ATTACK,
    ACTION_TYPE.ATTACK,
    ACTION_TYPE.ATTACK,
    ACTION_TYPE.ATTACK,
    ACTION_TYPE.ATTACK,
    ACTION_TYPE.ATTACK,
    ACTION_TYPE.ATTACK,
    ACTION_TYPE.ATTACK,
    ACTION_TYPE.ATTACK,
    ACTION_TYPE.ATTACK,
    ACTION_TYPE.ATTACK,
    ACTION_TYPE.ATTACK,
    ACTION_TYPE.ATTACK,
    ACTION_TYPE.ATTACK,
    ACTION_TYPE.ATTACK,
    ACTION_TYPE.ATTACK,
    ACTION_TYPE.ATTACK,
    ACTION_TYPE.ATTACK,
    ACTION_TYPE.ATTACK,
    ACTION_TYPE.ATTACK,
]

export const PLAYER01 = {
    name: "tikinnnn",
    hp: 10,
    mp: 40,
    str: 50,
    def: 0,
    speed: 300,
    actions: P1_ACTION_LIST,
    image: "player.svg"
}
