import { ACTION_TYPE, ActionType } from "@/constants/type";

export const P2_ACTION_LIST: ActionType[] = [
    ACTION_TYPE.GUARD,
    ACTION_TYPE.GUARD,
    ACTION_TYPE.GUARD,
    ACTION_TYPE.GUARD,
    ACTION_TYPE.GUARD,
    ACTION_TYPE.GUARD,
    ACTION_TYPE.GUARD,
    ACTION_TYPE.GUARD,
    ACTION_TYPE.GUARD,
    ACTION_TYPE.GUARD,
    ACTION_TYPE.GUARD,
    ACTION_TYPE.GUARD,
    ACTION_TYPE.GUARD,
    ACTION_TYPE.GUARD,
    ACTION_TYPE.GUARD,ACTION_TYPE.GUARD,
    ACTION_TYPE.GUARD,ACTION_TYPE.GUARD,ACTION_TYPE.GUARD,ACTION_TYPE.GUARD,ACTION_TYPE.GUARD,ACTION_TYPE.GUARD,ACTION_TYPE.GUARD,ACTION_TYPE.GUARD,ACTION_TYPE.GUARD,ACTION_TYPE.GUARD,ACTION_TYPE.GUARD,ACTION_TYPE.GUARD,ACTION_TYPE.GUARD,ACTION_TYPE.ATTACK]

export const PLAYER02 = {
    name: "じゅなてぇてぇ",
    hp: 400,
    mp: 0,
    str: 0,
    def: 0,
    speed: 0,
    actions: P2_ACTION_LIST,
    image: "フリーナ.jpg"
}
