version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql-db-container
    hostname: db-server
    volumes:
      - mysql-db-store:/var/lib/mysql:rw
      - ./dokcer.mysql.8.0/logs:/var/log/mysql:rw
      - ./dokcer.mysql.8.0/my.cnf:/etc/mysql/conf.d/my.cnf:rw
      - ./dokcer.mysql.8.0/initdb:/docker-entrypoint-initdb.d:rw
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=temp_app_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - TZ=Asia/Tokyo
    ports:
      - 3306:3306/tcp
    command: --innodb-use-native-aio=0

volumes:
  mysql-db-store:
